# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Mastodon Factory\Documents\myoutro\src\outroapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 470)
        MainWindow.setMinimumSize(QtCore.QSize(800, 470))
        MainWindow.setMaximumSize(QtCore.QSize(800, 470))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color: rgb(20, 20, 20);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setStyleSheet("background-color: rgb(49, 49, 49);\n"
"color: rgb(181, 181, 181);\n"
"border:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(0, 50, 150, 50))
        self.toolButton.setMinimumSize(QtCore.QSize(150, 40))
        self.toolButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.toolButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolButton.setStyleSheet("QToolButton {\n"
"    padding-left:-100px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
" }")
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Mastodon Factory\\Documents\\myoutro\\src\\media/icons/icons8-menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(25, 25))
        self.toolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(0, 100, 150, 50))
        self.toolButton_2.setMinimumSize(QtCore.QSize(150, 40))
        self.toolButton_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.toolButton_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolButton_2.setStyleSheet("QToolButton {\n"
"    font: 10pt \"MS UI Gothic\";\n"
"    padding-left:10px;\n"
"    border : solid white;\n"
"    font-weight: bold;\n"
"    border-width : 0px 0px 0px 2px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
" }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Mastodon Factory\\Documents\\myoutro\\src\\media/icons/icons8-home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_2.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setGeometry(QtCore.QRect(0, 150, 150, 50))
        self.toolButton_3.setMinimumSize(QtCore.QSize(150, 40))
        self.toolButton_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.toolButton_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolButton_3.setStyleSheet("QToolButton {\n"
"    padding-left:10px;\n"
"    font: 10pt \"MS UI Gothic\";\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
" }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Mastodon Factory\\Documents\\myoutro\\src\\media/icons/icons8-music.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_3.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame)
        self.toolButton_4.setGeometry(QtCore.QRect(0, 200, 150, 51))
        self.toolButton_4.setMinimumSize(QtCore.QSize(150, 40))
        self.toolButton_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.toolButton_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolButton_4.setStyleSheet("QToolButton {\n"
"    padding-left:10px;\n"
"    font: 10pt \"MS UI Gothic\";\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
" }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Mastodon Factory\\Documents\\myoutro\\src\\media/icons/icons8-image-gallery-24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_4.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(260, 140, 200, 200))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 100px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 150, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Mastodon Factory\\Documents\\myoutro\\src\\media/images/shutdown_vector_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(200, 200))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_2.setText(_translate("MainWindow", "       Home"))
        self.toolButton_3.setText(_translate("MainWindow", "       Audio"))
        self.toolButton_4.setText(_translate("MainWindow", "       Image"))
